syntax = "proto3";

package proto.user;

option java_package = "proto";
option java_multiple_files = true;

service UserService {

  rpc Register(RegisterRequest)
      returns (RegisterResponse);

  rpc Login(LoginRequest)
      returns (LoginResponse);

  rpc Logout(LogoutRequest)
      returns (LogoutResponse);

  rpc FindById(FindByIdRequest)
      returns (FindByIdResponse);

  rpc FindAll(FindAllRequest)
      returns (FindAllResponse);

}

message UserResponse {

  int64 id = 1;
  string login_id = 2;
  string username = 3;

}

message RegisterRequest {

  string login_id = 2;
  string password = 3;
  string username = 4;

}

message RegisterResponse {

  int64 id = 1;

}

message LoginRequest {

  string login_id = 1;
  string password = 2;

}

message LoginResponse {

  string access_token = 1;
  string refresh_token = 2;
  UserResponse user = 3;

}

message LogoutRequest {

  int64 id = 1;

}

message LogoutResponse {

}

message FindByIdRequest {

  int64 id = 1;

}

message FindByIdResponse {

}

message FindAllRequest {

}

message FindAllResponse {

  repeated UserResponse users = 1;

}